#!/usr/bin/env bash
# script that displays information on domain and its subdomain
# contain at least one function and display domain info as a string

display_info () {
	details=$(dig "$2.$1" | grep -A1 'ANSWER SECTION:' | tail -n 1)
	subdomain=$(echo "$details" | awk -F '.' '{print $1}')
	record_type=$(echo "$details" | awk -F ' ' '{print $4}')
	destination=$(echo "$details" | awk -F ' ' '{print $5}')
	echo The subdomain "$subdomain" is a "$record_type" record and points to "$destination"
}

if [ "$#" == 1 ]
then
	display_info "$1" "www"
	display_info "$1" "lb-01"
	display_info "$1" "web-01"
	display_info "$1" "web-02"
elif [ "$#" == 2 ]
then
	display_info "$1" "$2"
fi
