#!/usr/bin/env bash
# configure a web server to display "hello world" and listen to port 80

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "server {
	listen 80 default_server;

	root /var/www.html;
	index index.html;

	location /redirect_me {
		return 301 https://www.digitalocean.com/community/;
	}
}" > default_file
sudo mv -f default_file /etc/nginx/sites-enabled/default
sudo service nginx restart

