#!/usr/bin/env bash
# script that configure server with its custom HTTP header

apt-get -y update
apt-get -y upgrade
apt-get -y install nginx
ufw allow "Nginx HTTP"
service nginx start
sed -i "s/sendfile on;/add_header X-Served-By $(hostname);\n\tsendfile on;/" /etc/nginx/nginx.conf
service nginx restart

