#!/usr/bin/env bash
# script that debug and configures nginx server to listen to port 80
apt-get -y install socat | tee /dev/null > /dev/null 2>&1
sudo socat TCP-LISTEN:80,fork TCP:localhost:8080 > /dev/null 2>&1 &
